apiVersion: 1
datasources:
  - name: VictoriaMetrics
    uid: victoriametrics
    type: prometheus
    access: proxy
    url: http://vm:8428
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "1s"
      httpMethod: POST
